// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	http "net/http"
)

func AnyHttpRequest() http.Request {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(http.Request))(nil)).Elem()))
	var nullValue http.Request
	return nullValue
}

func EqHttpRequest(value http.Request) http.Request {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue http.Request
	return nullValue
}
