// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	io "io"
)

func AnyIoReadCloser() io.ReadCloser {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(io.ReadCloser))(nil)).Elem()))
	var nullValue io.ReadCloser
	return nullValue
}

func EqIoReadCloser(value io.ReadCloser) io.ReadCloser {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue io.ReadCloser
	return nullValue
}
