// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"github.com/petergtz/pegomock"
	"reflect"
)

func AnyMapOfStringToEmptyUnnamedStruct() map[string]struct{} {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(map[string]struct{}))(nil)).Elem()))
	var nullValue map[string]struct{}
	return nullValue
}

func EqMapOfStringToEmptyUnnamedStruct(value map[string]struct{}) map[string]struct{} {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue map[string]struct{}
	return nullValue
}

func NotEqMapOfStringToEmptyUnnamedStruct(value map[string]struct{}) map[string]struct{} {
	pegomock.RegisterMatcher(&pegomock.NotEqMatcher{Value: value})
	var nullValue map[string]struct{}
	return nullValue
}

func MapOfStringToEmptyUnnamedStructThat(matcher pegomock.ArgumentMatcher) map[string]struct{} {
	pegomock.RegisterMatcher(matcher)
	var nullValue map[string]struct{}
	return nullValue
}
