// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"github.com/petergtz/pegomock"
	"reflect"

	http "net/http"
)

func AnyMapOfStringToHttpRequest() map[string]http.Request {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(map[string]http.Request))(nil)).Elem()))
	var nullValue map[string]http.Request
	return nullValue
}

func EqMapOfStringToHttpRequest(value map[string]http.Request) map[string]http.Request {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue map[string]http.Request
	return nullValue
}

func NotEqMapOfStringToHttpRequest(value map[string]http.Request) map[string]http.Request {
	pegomock.RegisterMatcher(&pegomock.NotEqMatcher{Value: value})
	var nullValue map[string]http.Request
	return nullValue
}

func MapOfStringToHttpRequestThat(matcher pegomock.ArgumentMatcher) map[string]http.Request {
	pegomock.RegisterMatcher(matcher)
	var nullValue map[string]http.Request
	return nullValue
}
