// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	
http "net/http"
)

func AnyMapOfStringToHttpRequest() map[string]http.Request {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(map[string]http.Request))(nil)).Elem()))
	var nullValue map[string]http.Request
	return nullValue
}

func EqMapOfStringToHttpRequest(value map[string]http.Request) map[string]http.Request {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue map[string]http.Request
	return nullValue
}
