// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"github.com/petergtz/pegomock"
	"reflect"
)

func AnyRecvChanOfString() <-chan string {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(<-chan string))(nil)).Elem()))
	var nullValue <-chan string
	return nullValue
}

func EqRecvChanOfString(value <-chan string) <-chan string {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue <-chan string
	return nullValue
}

func NotEqRecvChanOfString(value <-chan string) <-chan string {
	pegomock.RegisterMatcher(&pegomock.NotEqMatcher{Value: value})
	var nullValue <-chan string
	return nullValue
}

func RecvChanOfStringThat(matcher pegomock.ArgumentMatcher) <-chan string {
	pegomock.RegisterMatcher(matcher)
	var nullValue <-chan string
	return nullValue
}
