// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	
)

func AnySendChanOfError() chan<- error {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(chan<- error))(nil)).Elem()))
	var nullValue chan<- error
	return nullValue
}

func EqSendChanOfError(value chan<- error) chan<- error {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue chan<- error
	return nullValue
}
