// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"github.com/petergtz/pegomock"
	"reflect"
)

func AnySendChanOfError() chan<- error {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(chan<- error))(nil)).Elem()))
	var nullValue chan<- error
	return nullValue
}

func EqSendChanOfError(value chan<- error) chan<- error {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue chan<- error
	return nullValue
}

func NotEqSendChanOfError(value chan<- error) chan<- error {
	pegomock.RegisterMatcher(&pegomock.NotEqMatcher{Value: value})
	var nullValue chan<- error
	return nullValue
}

func SendChanOfErrorThat(matcher pegomock.ArgumentMatcher) chan<- error {
	pegomock.RegisterMatcher(matcher)
	var nullValue chan<- error
	return nullValue
}
